### ISSUE TITLE
create_task is broken with crowdcrafting.org REST API

### ISSUE THREAD

**Issue by thisisdhaas** [PyBossa/pybossa-client#21]
Currently, running `pbclient.create_task(project_id, info)` against the crowdcrafting.org pybossa server fails with an HTTP 400 error 'Reserved Keys in Payload'.

A bit of inspection shows that pbclient is injecting `state=0` into the Task object (https://github.com/PyBossa/pybossa-client/blob/master/pbclient/__init__.py#L448), which is a reserved keyword in the pybossa API, causing the exception (https://github.com/PyBossa/pybossa/blob/fbdd27a6dde7b2965493cc221082be5a8066d01f/pybossa/api/task.py#L35).

To reproduce:

    >>> import pbclient
    >>> pbclient.set('endpoint', 'http://crowdcrafting.org')
    >>> pbclient.set('api_key', 'API_KEY_HERE')
    >>> pbclient.create_project('myproject', 'myproj', 'fancy description')
    >>> project = pbclient.find_project(short_name='myproj')[0]
    >>> project.info['task_presenter'] = open('template.html').read() # template.html contains some HTML
    >>> project = pbclient.update_project(project)
    >>> task_info = { }  #...some stuff that fits into template.html
    >>> print pbclient.create_task(project.id, task_info)
    {u'status': u'failed', u'target': u'task', u'exception_msg': u'Reserved keys in payload', u'status_code': 400, u'exception_cls': u'BadRequest', u'action': u'POST’}

Thanks @slgarden, @FadyShoukry, @palimpsests, @r19m89s for helping uncover the issue.

**Comment by teleyinex** [comment]
Hi @thisisdhaas 

First of all, apologies for not seeing this before. That issue is regarding an error that we've on PyBossa server that got fixed (overriding some reserved variables). Then, you get that error because pybossa-client is not updated to remove those and send the request properly. Can you test again?

**Comment by thisisdhaas** [comment]
Also sorry for the slow response. On the latest version of pbclient, I can't reproduce the error. Thanks!

**Comment by teleyinex** [comment]
No problem. And happy to know that latest version works well :-)
